# Blueberry Containerfile
# Minimal Fedora IoT-based server image for aarch64 SBCs

ARG FEDORA_VERSION="${FEDORA_VERSION:-44}"
ARG ARCH="${ARCH:-aarch64}"
ARG IMAGE_REGISTRY="${IMAGE_REGISTRY:-quay.io}"

# Allow build scripts to be referenced without being copied into the final image
FROM scratch AS ctx
COPY . /

# Base Image
FROM ${IMAGE_REGISTRY}/fedora/fedora-iot:${FEDORA_VERSION}-${ARCH}

## Other possible base images include:
# FROM ghcr.io/ublue-os/bazzite:latest
# FROM ghcr.io/ublue-os/bluefin-nvidia:stable
# 
# ... and so on, here are more base images
# Universal Blue Images: https://github.com/orgs/ublue-os/packages
# Fedora base image: quay.io/fedora/fedora-bootc:41
# CentOS base images: quay.io/centos-bootc/centos-bootc:stream10

### [IM]MUTABLE /opt
## Some bootable images, like Fedora, have /opt symlinked to /var/opt, in order to
## make it mutable/writable for users. However, some packages write files to this directory,
## thus its contents might be wiped out when bootc deploys an image, making it troublesome for
## some packages. Eg, google-chrome, docker-desktop.
##
## Uncomment the following line if one desires to make /opt immutable and be able to be used
## by the package manager.

# RUN rm /opt && mkdir /opt

### SYSTEM CONFIGURATION
## Copy system configuration files into the image

COPY system_files/etc /etc/
COPY system_files/usr /usr/

### PACKAGE INSTALLATION
## Install packages and configure system services

RUN --mount=type=bind,from=ctx,src=/,dst=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/install-blueberry.sh

### CLEANUP
## Clean up image layers to reduce size

RUN --mount=type=bind,from=ctx,src=/,dst=/ctx \
    /ctx/cleanup.sh

### LINTING
## Verify final image and contents are correct

RUN bootc container lint

### METADATA
## Image labels for OCI compatibility

LABEL org.opencontainers.image.title="Blueberry"
LABEL org.opencontainers.image.description="Minimal Fedora IoT-based server image for aarch64 SBCs"
LABEL org.opencontainers.image.source="https://github.com/philbudden/blueberry"
